import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Logout handler
const handleLogout = () => {
  localStorage.removeItem('token'); // Clear the token
  router.replace('/'); // Redirect to login page
};

// Show Logout button only on protected pages
const showLogoutButton = pathname !== '/' && pathname !== '/register';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>  
          {showLogoutButton && (
            <button onClick={handleLogout}>Logout</button>
          )}
          <h1> 
            <Link href="/">Home</Link>
            <Link href="/register">Register</Link>
            <Link href="/login">Login</Link>
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
